// Database Cleanup Script - Removes all test/fake data while preserving admin and core settings
const { db } = require('./db');

function cleanDatabase({ keepSampleContacts = true } = {}) {
  console.log('🧹 Cleaning SendQueue database...');

  db.exec('BEGIN TRANSACTION;');
  try {
    // 1. Clear test queues, campaigns, recipients, and audit logs
    const delAudit = db.prepare('DELETE FROM audit_events').run();
    const delRecipients = db.prepare('DELETE FROM campaign_recipients').run();
    const delCampaigns = db.prepare('DELETE FROM campaigns').run();
    const delSuppression = db.prepare('DELETE FROM suppression_list').run();
    const delMockInbox = db.prepare('DELETE FROM mock_inbox').run();

    console.log(`  ✔ Cleared ${delCampaigns.changes} campaigns and ${delRecipients.changes} recipient queue jobs.`);
    console.log(`  ✔ Cleared ${delAudit.changes} audit events and ${delSuppression.changes} suppression entries.`);
    console.log(`  ✔ Cleared ${delMockInbox.changes} mock inbox messages.`);

    // 2. Remove test groups (e.g. Q4 Retailers)
    db.prepare("DELETE FROM groups WHERE name LIKE 'Q4 Retailers%' OR name LIKE 'Test%'").run();

    // 3. Remove fake/test contacts generated by test suites
    db.prepare(`
      DELETE FROM contacts 
      WHERE email LIKE 'test.%' 
         OR email LIKE 'valid%' 
         OR email LIKE 'recipient_%' 
         OR email LIKE 'unsub_%' 
         OR email LIKE 'bounce_%' 
         OR email LIKE 'complaint_%' 
         OR email LIKE 'suppress_%'
    `).run();

    // Clean orphaned junction rows
    db.prepare('DELETE FROM contact_groups WHERE contact_id NOT IN (SELECT id FROM contacts) OR group_id NOT IN (SELECT id FROM groups)').run();

    // Reset status of remaining sample contacts to 'active'
    db.prepare("UPDATE contacts SET status = 'active'").run();

    db.exec('COMMIT;');
    console.log('✨ Database cleanup completed successfully!');
  } catch (err) {
    db.exec('ROLLBACK;');
    console.error('❌ Cleanup failed:', err);
    throw err;
  }
}

if (require.main === module) {
  cleanDatabase();
}

module.exports = { cleanDatabase };
